package filestore

import (
	"context"
	"io"
)

// Backend is the storage abstraction for file bytes.
// Implementations: LocalFS (this package), S3 (future).
// Keys are always slugs generated by internal/slug — never user-supplied filenames.
type Backend interface {
	// Write stores the content from r under the given key.
	// Overwrites existing content if key already exists.
	Write(ctx context.Context, key string, r io.Reader) error

	// Read returns a ReadCloser for the content stored under key.
	// Returns os.ErrNotExist if the key does not exist.
	// Caller must close the returned ReadCloser.
	Read(ctx context.Context, key string) (io.ReadCloser, error)

	// Delete removes the content stored under key.
	// Returns nil if the key does not exist (idempotent).
	Delete(ctx context.Context, key string) error

	// Exists reports whether the given key has stored content.
	Exists(ctx context.Context, key string) (bool, error)
}
